import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'config_service.dart';
import '../models/chat_message.dart';
import '../models/drive_file.dart';

/// Exception thrown when AI chat API calls fail
class AIChatException implements Exception {
  final String message;
  final int? statusCode;

  AIChatException(this.message, [this.statusCode]);

  @override
  String toString() => 'AIChatException: $message (Status: $statusCode)';
}

/// Service for AI chat with RAG
class AIChatService {
  static final AIChatService _instance = AIChatService._internal();
  factory AIChatService() => _instance;
  AIChatService._internal();

  final _config = ConfigService();

  String get _baseUrl => _config.apiBaseUrl;

  /// Send a chat message with RAG and source filtering
  Future<ChatMessage> sendMessage({
    required String question,
    required String userId,
    List<String>? selectedFileIds,
    int topK = 5,
    List<ChatMessage>? history,
    List<DriveFile>? availableFiles,
  }) async {
    try {
      final requestBody = {
        'question': question,
        'user_id': userId,
        'top_k': topK,
      };

      if (selectedFileIds != null && selectedFileIds.isNotEmpty) {
        requestBody['selected_file_ids'] = selectedFileIds;
      }

      if (history != null && history.isNotEmpty) {
        requestBody['history'] = history
            .map(
              (msg) => {
                'role': msg.isUser ? 'user' : 'assistant',
                'content': msg.content,
              },
            )
            .toList();
      }

      if (availableFiles != null && availableFiles.isNotEmpty) {
        requestBody['available_files'] = availableFiles
            .map((file) => {'id': file.id, 'name': file.name})
            .toList();
      }

      final response = await http.post(
        Uri.parse('$_baseUrl/api/ai/chat-rag'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode(requestBody),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);

        // Parse citations
        final citationsList = data['citations'] as List? ?? [];
        final citations = citationsList
            .map((c) => Citation.fromJson(c as Map<String, dynamic>))
            .toList();

        // Create chat message from response
        // Use current time to ensure proper ordering with user messages
        final responseTime = DateTime.now();
        return ChatMessage(
          id: '${responseTime.millisecondsSinceEpoch}_ai',
          content: data['message'] as String,
          isUser: false,
          timestamp: responseTime,
          citations: citations.isNotEmpty ? citations : null,
        );
      } else if (response.statusCode == 429) {
        throw AIChatException(
          'Rate limit exceeded. Please try again later.',
          response.statusCode,
        );
      } else if (response.statusCode == 503) {
        throw AIChatException(
          'AI service temporarily unavailable. Please try again later.',
          response.statusCode,
        );
      } else {
        final errorData = jsonDecode(response.body);
        throw AIChatException(
          errorData['detail'] ?? 'Failed to send message',
          response.statusCode,
        );
      }
    } catch (e) {
      if (e is AIChatException) rethrow;
      debugPrint('Failed to send chat message: $e');
      throw AIChatException('Failed to send message: $e');
    }
  }

  /// Save chat response as Markdown note to Google Drive
  /// Returns the created file ID
  Future<String> saveChatAsNote({
    required ChatMessage message,
    required String userId,
    String? customFileName,
  }) async {
    if (message.isUser) {
      throw AIChatException('Cannot save user messages as notes');
    }

    // Generate markdown content
    final buffer = StringBuffer();
    buffer.writeln('# AI Chat Response');
    buffer.writeln();
    buffer.writeln('**Date:** ${_formatDate(message.timestamp)}');
    buffer.writeln();
    buffer.writeln('## Response');
    buffer.writeln();
    buffer.writeln(message.content);
    buffer.writeln();

    // Add citations if available
    if (message.citations != null && message.citations!.isNotEmpty) {
      buffer.writeln('## Sources');
      buffer.writeln();
      for (var i = 0; i < message.citations!.length; i++) {
        final citation = message.citations![i];
        buffer.writeln(
          '${i + 1}. **${citation.fileName}** (Page ${citation.pageNumber})',
        );
        if (citation.snippet.isNotEmpty) {
          buffer.writeln('   > ${citation.snippet}');
        }
      }
      buffer.writeln();
    }

    buffer.writeln('---');
    buffer.writeln('*Generated by ScholarMate AI Chat*');

    return buffer.toString();
  }

  String _formatDate(DateTime date) {
    final months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    return '${months[date.month - 1]} ${date.day}, ${date.year} at ${date.hour.toString().padLeft(2, '0')}:${date.minute.toString().padLeft(2, '0')}';
  }

  /// Check if backend is available
  Future<bool> checkHealth() async {
    try {
      final response = await http
          .get(Uri.parse('$_baseUrl/api/health'))
          .timeout(const Duration(seconds: 5));

      return response.statusCode == 200;
    } catch (e) {
      debugPrint('Health check failed: $e');
      return false;
    }
  }
}
