[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.3",
    "email-validator>=2.3.0",
    "fastapi>=0.119.1",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "requests>=2.32.5",
    "supabase>=2.22.0",
    "uvicorn>=0.38.0",
]
